build_environment: &build_environment
  working_directory: ~/repo
  docker:
    - image: circleci/node:12

commands:
  update_npm_and_install_deps:
    steps:
      - restore_cache:
          name: Restore npm cache
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Update npm
          command: 'if [ "$(npm -v)" = "6.9.0" ]; then echo "Up to date"; else sudo npm i -g npm@6.9.0; fi'
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          name: Save npm cache
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

version: 2.1

jobs:
  build_and_deploy:
    <<: *build_environment
    steps:
      - checkout
      - update_npm_and_install_deps
      - run:
          name: Build code
          command: npm run build
      - run:
          name: Deploy code
          command: npm run deploy
      - run:
          name: Ping google
          command: npm run ping-google


workflows:
  version: 2
  ci:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - master
